# https://packaging.python.org/en/latest/guides/writing-pyproject-toml
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# https://setuptools.pypa.io/en/latest/userguide/datafiles.html

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

